apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmp-engine
  namespace: pspd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openmp-engine
  template:
    metadata:
      labels:
        app: openmp-engine
    spec:
      containers:
      - name: openmp-engine
        image: vm1:5000/openmpmpiengine:latest
        ports:
        - containerPort: 8081
        env:
        - name: OMP_NUM_THREADS
          value: "4"
        imagePullPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - openmp-engine
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: openmpmpi-service
  namespace: pspd
spec:
  selector:
    app: openmp-engine
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
