apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: pspd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.4.1
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: "master"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: pspd
spec:
  selector:
    app: spark-master
  ports:
  - port: 7077
    targetPort: 7077
  type: ClusterIP
